---
- hosts: localhost
  tasks:
    - name: create a file
      lineinfile:
        path: /home/ansible/hostname
        create: yes
        line: "{{ ansible_hostname }}"
    - name: access magic variables
      lineinfile:
        path: /home/ansible/hostname
        line: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"
