---
# handlers file for prometheus
- name: restart prometheus
  service: 
    name: prometheus 
    state: restarted
    daemon_reload: yes
    enabled: yes  

- name: restart node-exporter
  service: 
    name: node-exporter 
    state: restarted
    daemon_reload: yes
    enabled: yes 
