---
# tasks file for prometheus
- name: Install software
  dnf:
    name: tar
    state: present

- name: Create user for prometheus
  user:
    name: "{{ prometheus_user }}"  # Username
    state: present  # Ensure the user is present
    createhome: no  # Create the user's home directory  
    shell: /usr/sbin/nologin
    append: yes
  become: true  

- name: Create user for node-exporter
  user:
    name: "{{ node_exporter_user }}"  # Username
    state: present  # Ensure the user is present
    createhome: no  # Create the user's home directory  
    shell: /usr/sbin/nologin
    append: yes
  become: true   

- name: Create installation folder in etc
  file:
    path: "{{ prometheus_dest_dir }}"
    state: directory
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"    
    mode: '0775'
    recurse: yes

- name: Create data folder
  file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"     
    mode: '0775'
    recurse: yes

- name: Download/unarchive Packages for prometheus
  unarchive:
    src: "{{ prometheus_download_url }}"
    dest: /tmp
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}" 
    remote_src: yes
    creates: "{{ prometheus_download_dir }}"

- name: Download/unarchive Packages for node-exporter
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    remote_src: yes
    creates: "{{ node_exporter_download_dir }}"

- name: Copying the service binary for prometheus
  copy:
    src: "{{ prometheus_download_dir }}/"
    dest: /usr/local/bin/
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"    
    mode: '0775'
    remote_src: yes
  with_items:
   - prometheus
   - promtool 
     
- name: Copying the console binary
  copy:
    src: "{{ prometheus_download_dir }}/"
    dest: "{{ prometheus_dest_dir }}"
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"    
    mode: '0775'
    remote_src: yes
  with_items:
   - consoles
   - console_libraries 

- name: Copying the service binary for node-exporter
  copy:
    src: "{{ node_exporter_download_dir }}/"
    dest: /usr/local/bin/
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"   
    mode: '0775'
    remote_src: yes
  with_items:
   - node_exporter    

- name: Removing the tar file of prometheus
  file:
    path: "{{ prometheus_download_dir }}"
    state: absent

- name: Removing the tar file of node-exporter
  file:
    path: "{{ node_exporter_download_dir }}"
    state: absent

- name: Create prometheus systemd service file
  template:
    src: templates/prometheus.service.j2
    dest: "{{ service_dest_dir }}/prometheus.service"   

- name: Create prometheus systemd service file
  template:
    src: templates/node-exporter.service.j2
    dest: "{{ service_dest_dir }}/node-exporter.service"  

- name: Copying the scrape config
  template:  
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_dest_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}" 
    mode: '0775'
  notify:
  - restart node-exporter
  - restart prometheus 
